//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS2.Common.Business.Wssmslink {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wssmslink.LinkWSSoap")]
    public interface LinkWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int BatchSend(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportFail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetReportFail(string CorpID, string Pwd, string cell);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Reg(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdPwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdPwd(string CorpID, string Pwd, string NewPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdReg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdReg(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelSum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SelSum(string CorpID, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Send(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get(string CorpID, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnReg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UnReg(string CorpID, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ChargeUp(string CorpID, string Pwd, string CardNo, string CardPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgentChangeAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AgentChangeAccount(string LoginName, string LoginPwd, string CorpID, int SmsBalance, int MmsBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BalanceMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BalanceMMS(string CorpID, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMMS(string CorpID, string Pwd, string Mobile, string Base64Content, string Title, string ExtCode, string SendTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchSendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BatchSendMMS(string CorpID, string Pwd, string Mobiles, string Base64Content, string Title, string ExtCode, string SendTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportFailMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetReportFailMMS(string CorpID, string Pwd, string cell);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMMS(string CorpID, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeUpMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChargeUpMMS(string CorpID, string Pwd, string CardNo, string CardPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgentMakeAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AgentMakeAccount(string LoginName, string LoginPwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo, string CorpID, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetReportSMS(string CorpID, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetReportMMS(string CorpID, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Send2(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMMS2(string CorpID, string Pwd, string Mobile, string Base64Content, string Title, string ExtCode, string SendTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchSend2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BatchSend2(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchSendMMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BatchSendMMS2(string CorpID, string Pwd, string Mobiles, string Base64Content, string Title, string ExtCode, string SendTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LinkWSSoapChannel : ETS2.Common.Business.Wssmslink.LinkWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LinkWSSoapClient : System.ServiceModel.ClientBase<ETS2.Common.Business.Wssmslink.LinkWSSoap>, ETS2.Common.Business.Wssmslink.LinkWSSoap {
        
        public LinkWSSoapClient() {
        }
        
        public LinkWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LinkWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public int BatchSend(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime) {
            return base.Channel.BatchSend(CorpID, Pwd, Mobile, Content, Cell, SendTime);
        }
        
        public string GetReportFail(string CorpID, string Pwd, string cell) {
            return base.Channel.GetReportFail(CorpID, Pwd, cell);
        }
        
        public int Reg(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo) {
            return base.Channel.Reg(CorpID, Pwd, CorpName, LinkMan, Tel, Mobile, Email, Memo);
        }
        
        public int UpdPwd(string CorpID, string Pwd, string NewPwd) {
            return base.Channel.UpdPwd(CorpID, Pwd, NewPwd);
        }
        
        public int UpdReg(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo) {
            return base.Channel.UpdReg(CorpID, Pwd, CorpName, LinkMan, Tel, Mobile, Email, Memo);
        }
        
        public int SelSum(string CorpID, string Pwd) {
            return base.Channel.SelSum(CorpID, Pwd);
        }
        
        public int Send(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime) {
            return base.Channel.Send(CorpID, Pwd, Mobile, Content, Cell, SendTime);
        }
        
        public string Get(string CorpID, string Pwd) {
            return base.Channel.Get(CorpID, Pwd);
        }
        
        public int UnReg(string CorpID, string Pwd) {
            return base.Channel.UnReg(CorpID, Pwd);
        }
        
        public int ChargeUp(string CorpID, string Pwd, string CardNo, string CardPwd) {
            return base.Channel.ChargeUp(CorpID, Pwd, CardNo, CardPwd);
        }
        
        public string AgentChangeAccount(string LoginName, string LoginPwd, string CorpID, int SmsBalance, int MmsBalance) {
            return base.Channel.AgentChangeAccount(LoginName, LoginPwd, CorpID, SmsBalance, MmsBalance);
        }
        
        public string BalanceMMS(string CorpID, string Pwd) {
            return base.Channel.BalanceMMS(CorpID, Pwd);
        }
        
        public string SendMMS(string CorpID, string Pwd, string Mobile, string Base64Content, string Title, string ExtCode, string SendTime) {
            return base.Channel.SendMMS(CorpID, Pwd, Mobile, Base64Content, Title, ExtCode, SendTime);
        }
        
        public string BatchSendMMS(string CorpID, string Pwd, string Mobiles, string Base64Content, string Title, string ExtCode, string SendTime) {
            return base.Channel.BatchSendMMS(CorpID, Pwd, Mobiles, Base64Content, Title, ExtCode, SendTime);
        }
        
        public string GetReportFailMMS(string CorpID, string Pwd, string cell) {
            return base.Channel.GetReportFailMMS(CorpID, Pwd, cell);
        }
        
        public string GetMMS(string CorpID, string Pwd) {
            return base.Channel.GetMMS(CorpID, Pwd);
        }
        
        public string ChargeUpMMS(string CorpID, string Pwd, string CardNo, string CardPwd) {
            return base.Channel.ChargeUpMMS(CorpID, Pwd, CardNo, CardPwd);
        }
        
        public string AgentMakeAccount(string LoginName, string LoginPwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo, string CorpID, string Pass) {
            return base.Channel.AgentMakeAccount(LoginName, LoginPwd, CorpName, LinkMan, Tel, Mobile, Email, Memo, CorpID, Pass);
        }
        
        public string GetReportSMS(string CorpID, string Pwd) {
            return base.Channel.GetReportSMS(CorpID, Pwd);
        }
        
        public string GetReportMMS(string CorpID, string Pwd) {
            return base.Channel.GetReportMMS(CorpID, Pwd);
        }
        
        public string Send2(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime) {
            return base.Channel.Send2(CorpID, Pwd, Mobile, Content, Cell, SendTime);
        }
        
        public string SendMMS2(string CorpID, string Pwd, string Mobile, string Base64Content, string Title, string ExtCode, string SendTime) {
            return base.Channel.SendMMS2(CorpID, Pwd, Mobile, Base64Content, Title, ExtCode, SendTime);
        }
        
        public string BatchSend2(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime) {
            return base.Channel.BatchSend2(CorpID, Pwd, Mobile, Content, Cell, SendTime);
        }
        
        public string BatchSendMMS2(string CorpID, string Pwd, string Mobiles, string Base64Content, string Title, string ExtCode, string SendTime) {
            return base.Channel.BatchSendMMS2(CorpID, Pwd, Mobiles, Base64Content, Title, ExtCode, SendTime);
        }
    }
}
