// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: QMRequestDataSchema-2.0.2.xsd
// Creation Date: 2015-5-11 13:29:54
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://piao.qunar.com/2013/QMenpiaoRequestSchema";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonpersonCollection : ArrayList
	{
		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson Add(CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			base.Add(obj);
			return obj;
		}

		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson Add()
		{
			return Add(new CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson());
		}

		public void Insert(int index, CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			base.Remove(obj);
		}

		new public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson this[int index]
		{
			get { return (CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonpersonCollection : ArrayList
	{
		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson Add(CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			base.Add(obj);
			return obj;
		}

		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson Add()
		{
			return Add(new CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson());
		}

		public void Insert(int index, CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			base.Remove(obj);
		}

		new public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson this[int index]
		{
			get { return (CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class personCollection : ArrayList
	{
		public person Add(person obj)
		{
			base.Add(obj);
			return obj;
		}

		public person Add()
		{
			return Add(new person());
		}

		public void Insert(int index, person obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(person obj)
		{
			base.Remove(obj);
		}

		new public person this[int index]
		{
			get { return (person) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonpersonCollection : ArrayList
	{
		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson Add(PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			base.Add(obj);
			return obj;
		}

		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson Add()
		{
			return Add(new PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson());
		}

		public void Insert(int index, PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			base.Remove(obj);
		}

		new public PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson this[int index]
		{
			get { return (PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson) base[index]; }
			set { base[index] = value; }
		}
	}



	[XmlType(TypeName="ApplyOrderRefundByUserRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class ApplyOrderRefundByUserRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(orderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public orderInfo __orderInfo;
		
		[XmlIgnore]
		public orderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new orderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public ApplyOrderRefundByUserRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="orderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class orderInfo
	{

		[XmlElement(ElementName="partnerorderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerorderId;
		
		[XmlIgnore]
		public string partnerorderId
		{ 
			get { return __partnerorderId; }
			set { __partnerorderId = value; }
		}

		[XmlElement(ElementName="refundSeq",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundSeq;
		
		[XmlIgnore]
		public string refundSeq
		{ 
			get { return __refundSeq; }
			set { __refundSeq = value; }
		}

		[XmlElement(ElementName="orderPrice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderPrice;
		
		[XmlIgnore]
		public string orderPrice
		{ 
			get { return __orderPrice; }
			set { __orderPrice = value; }
		}

		[XmlElement(ElementName="orderQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderQuantity;
		
		[XmlIgnore]
		public string orderQuantity
		{ 
			get { return __orderQuantity; }
			set { __orderQuantity = value; }
		}

		[XmlElement(ElementName="refundQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundQuantity;
		
		[XmlIgnore]
		public string refundQuantity
		{ 
			get { return __refundQuantity; }
			set { __refundQuantity = value; }
		}

		[XmlElement(ElementName="refundReason",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundReason;
		
		[XmlIgnore]
		public string refundReason
		{ 
			get { return __refundReason; }
			set { __refundReason = value; }
		}

		[XmlElement(ElementName="refundExplain",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundExplain;
		
		[XmlIgnore]
		public string refundExplain
		{ 
			get { return __refundExplain; }
			set { __refundExplain = value; }
		}

		[XmlElement(ElementName="orderRefundCharge",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderRefundCharge;
		
		[XmlIgnore]
		public string orderRefundCharge
		{ 
			get { return __orderRefundCharge; }
			set { __orderRefundCharge = value; }
		}

		public orderInfo()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderConsumedRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class NoticeOrderConsumedRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(NoticeOrderConsumedRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public NoticeOrderConsumedRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public NoticeOrderConsumedRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new NoticeOrderConsumedRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public NoticeOrderConsumedRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderConsumedRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class NoticeOrderConsumedRequestBodyorderInfo
	{

		[XmlElement(ElementName="partnerorderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerorderId;
		
		[XmlIgnore]
		public string partnerorderId
		{ 
			get { return __partnerorderId; }
			set { __partnerorderId = value; }
		}

		[XmlElement(ElementName="orderQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderQuantity;
		
		[XmlIgnore]
		public string orderQuantity
		{ 
			get { return __orderQuantity; }
			set { __orderQuantity = value; }
		}

		[XmlElement(ElementName="useQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __useQuantity;
		
		[XmlIgnore]
		public string useQuantity
		{ 
			get { return __useQuantity; }
			set { __useQuantity = value; }
		}

		[XmlElement(ElementName="consumeInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __consumeInfo;
		
		[XmlIgnore]
		public string consumeInfo
		{ 
			get { return __consumeInfo; }
			set { __consumeInfo = value; }
		}

		public NoticeOrderConsumedRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="RequestHeader",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class RequestHeader
	{

		[XmlElement(ElementName="application",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __application;
		
		[XmlIgnore]
		public string application
		{ 
			get { return __application; }
			set { __application = value; }
		}

		[XmlElement(ElementName="processor",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __processor;
		
		[XmlIgnore]
		public string processor
		{ 
			get { return __processor; }
			set { __processor = value; }
		}

		[XmlElement(ElementName="version",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __version;
		
		[XmlIgnore]
		public string version
		{ 
			get { return __version; }
			set { __version = value; }
		}

		[XmlElement(ElementName="bodyType",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __bodyType;
		
		[XmlIgnore]
		public string bodyType
		{ 
			get { return __bodyType; }
			set { __bodyType = value; }
		}

		[XmlElement(ElementName="createUser",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __createUser;
		
		[XmlIgnore]
		public string createUser
		{ 
			get { return __createUser; }
			set { __createUser = value; }
		}

		[XmlElement(ElementName="createTime",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __createTime;
		
		[XmlIgnore]
		public string createTime
		{ 
			get { return __createTime; }
			set { __createTime = value; }
		}

		[XmlElement(ElementName="supplierIdentity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __supplierIdentity;
		
		[XmlIgnore]
		public string supplierIdentity
		{ 
			get { return __supplierIdentity; }
			set { __supplierIdentity = value; }
		}

		public RequestHeader()
		{
		}
	}


	[XmlType(TypeName="GetOrderBySupplierRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class GetOrderBySupplierRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(ElementName="partnerOrderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerOrderId;
		
		[XmlIgnore]
		public string partnerOrderId
		{ 
			get { return __partnerOrderId; }
			set { __partnerOrderId = value; }
		}

		public GetOrderBySupplierRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderRefundApproveResultRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class NoticeOrderRefundApproveResultRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(NoticeOrderRefundApproveResultRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public NoticeOrderRefundApproveResultRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public NoticeOrderRefundApproveResultRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new NoticeOrderRefundApproveResultRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public NoticeOrderRefundApproveResultRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderRefundApproveResultRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class NoticeOrderRefundApproveResultRequestBodyorderInfo
	{

		[XmlElement(ElementName="partnerorderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerorderId;
		
		[XmlIgnore]
		public string partnerorderId
		{ 
			get { return __partnerorderId; }
			set { __partnerorderId = value; }
		}

		[XmlElement(ElementName="refundSeq",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundSeq;
		
		[XmlIgnore]
		public string refundSeq
		{ 
			get { return __refundSeq; }
			set { __refundSeq = value; }
		}

		[XmlElement(ElementName="orderQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderQuantity;
		
		[XmlIgnore]
		public string orderQuantity
		{ 
			get { return __orderQuantity; }
			set { __orderQuantity = value; }
		}

		[XmlElement(ElementName="refundQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundQuantity;
		
		[XmlIgnore]
		public string refundQuantity
		{ 
			get { return __refundQuantity; }
			set { __refundQuantity = value; }
		}

		[XmlElement(ElementName="refundJudgeMark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundJudgeMark;
		
		[XmlIgnore]
		public string refundJudgeMark
		{ 
			get { return __refundJudgeMark; }
			set { __refundJudgeMark = value; }
		}

		[XmlElement(ElementName="refundResult",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundResult;
		
		[XmlIgnore]
		public string refundResult
		{ 
			get { return __refundResult; }
			set { __refundResult = value; }
		}

		public NoticeOrderRefundApproveResultRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderAlreadyCashBackRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class NoticeOrderAlreadyCashBackRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(NoticeOrderAlreadyCashBackRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public NoticeOrderAlreadyCashBackRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public NoticeOrderAlreadyCashBackRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new NoticeOrderAlreadyCashBackRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public NoticeOrderAlreadyCashBackRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderAlreadyCashBackRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class NoticeOrderAlreadyCashBackRequestBodyorderInfo
	{

		[XmlElement(ElementName="partnerorderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerorderId;
		
		[XmlIgnore]
		public string partnerorderId
		{ 
			get { return __partnerorderId; }
			set { __partnerorderId = value; }
		}

		[XmlElement(ElementName="orderCashBackMoney",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderCashBackMoney;
		
		[XmlIgnore]
		public string orderCashBackMoney
		{ 
			get { return __orderCashBackMoney; }
			set { __orderCashBackMoney = value; }
		}

		public NoticeOrderAlreadyCashBackRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderEticketSendedRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class NoticeOrderEticketSendedRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(NoticeOrderEticketSendedRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public NoticeOrderEticketSendedRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public NoticeOrderEticketSendedRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new NoticeOrderEticketSendedRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public NoticeOrderEticketSendedRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderEticketSendedRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class NoticeOrderEticketSendedRequestBodyorderInfo
	{

		[XmlElement(ElementName="partnerorderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerorderId;
		
		[XmlIgnore]
		public string partnerorderId
		{ 
			get { return __partnerorderId; }
			set { __partnerorderId = value; }
		}

		[XmlElement(ElementName="eticketNo",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __eticketNo;
		
		[XmlIgnore]
		public string eticketNo
		{ 
			get { return __eticketNo; }
			set { __eticketNo = value; }
		}

		[XmlElement(ElementName="eticketSended",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __eticketSended;
		
		[XmlIgnore]
		public string eticketSended
		{ 
			get { return __eticketSended; }
			set { __eticketSended = value; }
		}

		public NoticeOrderEticketSendedRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="RequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class RequestBody
	{

		public RequestBody()
		{
		}
	}


	[XmlType(TypeName="CheckCreateOrderForAfterPaySyncRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class CheckCreateOrderForAfterPaySyncRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(CheckCreateOrderForAfterPaySyncRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CheckCreateOrderForAfterPaySyncRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public CheckCreateOrderForAfterPaySyncRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new CheckCreateOrderForAfterPaySyncRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public CheckCreateOrderForAfterPaySyncRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="CheckCreateOrderForAfterPaySyncRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class CheckCreateOrderForAfterPaySyncRequestBodyorderInfo
	{

		[XmlElement(ElementName="orderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderId;
		
		[XmlIgnore]
		public string orderId
		{ 
			get { return __orderId; }
			set { __orderId = value; }
		}

		[XmlElement(Type=typeof(product),ElementName="product",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public product __product;
		
		[XmlIgnore]
		public product product
		{
			get
			{
				if (__product == null) __product = new product();		
				return __product;
			}
			set {__product = value;}
		}

		[XmlElement(Type=typeof(contactPerson),ElementName="contactPerson",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public contactPerson __contactPerson;
		
		[XmlIgnore]
		public contactPerson contactPerson
		{
			get
			{
				if (__contactPerson == null) __contactPerson = new contactPerson();		
				return __contactPerson;
			}
			set {__contactPerson = value;}
		}

		[XmlElement(Type=typeof(visitPerson),ElementName="visitPerson",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public visitPerson __visitPerson;
		
		[XmlIgnore]
		public visitPerson visitPerson
		{
			get
			{
				if (__visitPerson == null) __visitPerson = new visitPerson();		
				return __visitPerson;
			}
			set {__visitPerson = value;}
		}

		[XmlElement(ElementName="orderQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderQuantity;
		
		[XmlIgnore]
		public string orderQuantity
		{ 
			get { return __orderQuantity; }
			set { __orderQuantity = value; }
		}

		[XmlElement(ElementName="orderPrice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderPrice;
		
		[XmlIgnore]
		public string orderPrice
		{ 
			get { return __orderPrice; }
			set { __orderPrice = value; }
		}

		[XmlElement(ElementName="orderCashBackMoney",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderCashBackMoney;
		
		[XmlIgnore]
		public string orderCashBackMoney
		{ 
			get { return __orderCashBackMoney; }
			set { __orderCashBackMoney = value; }
		}

		[XmlElement(ElementName="orderStatus",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderStatus;
		
		[XmlIgnore]
		public string orderStatus
		{ 
			get { return __orderStatus; }
			set { __orderStatus = value; }
		}

		[XmlElement(ElementName="orderRemark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderRemark;
		
		[XmlIgnore]
		public string orderRemark
		{ 
			get { return __orderRemark; }
			set { __orderRemark = value; }
		}

		[XmlElement(ElementName="orderSource",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderSource;
		
		[XmlIgnore]
		public string orderSource
		{ 
			get { return __orderSource; }
			set { __orderSource = value; }
		}

		public CheckCreateOrderForAfterPaySyncRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="product",Namespace=Declarations.SchemaVersion),Serializable]
	public class product
	{

		[XmlElement(ElementName="resourceId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __resourceId;
		
		[XmlIgnore]
		public string resourceId
		{ 
			get { return __resourceId; }
			set { __resourceId = value; }
		}

		[XmlElement(ElementName="productName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __productName;
		
		[XmlIgnore]
		public string productName
		{ 
			get { return __productName; }
			set { __productName = value; }
		}

		[XmlElement(ElementName="visitDate",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __visitDate;
		
		[XmlIgnore]
		public string visitDate
		{ 
			get { return __visitDate; }
			set { __visitDate = value; }
		}

		[XmlElement(ElementName="sellPrice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __sellPrice;
		
		[XmlIgnore]
		public string sellPrice
		{ 
			get { return __sellPrice; }
			set { __sellPrice = value; }
		}

		[XmlElement(ElementName="cashBackMoney",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __cashBackMoney;
		
		[XmlIgnore]
		public string cashBackMoney
		{ 
			get { return __cashBackMoney; }
			set { __cashBackMoney = value; }
		}

		public product()
		{
		}
	}


	[XmlType(TypeName="contactPerson",Namespace=Declarations.SchemaVersion),Serializable]
	public class contactPerson
	{

		[XmlElement(ElementName="name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlElement(ElementName="namePinyin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __namePinyin;
		
		[XmlIgnore]
		public string namePinyin
		{ 
			get { return __namePinyin; }
			set { __namePinyin = value; }
		}

		[XmlElement(ElementName="mobile",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __mobile;
		
		[XmlIgnore]
		public string mobile
		{ 
			get { return __mobile; }
			set { __mobile = value; }
		}

		[XmlElement(ElementName="email",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __email;
		
		[XmlIgnore]
		public string email
		{ 
			get { return __email; }
			set { __email = value; }
		}

		[XmlElement(ElementName="address",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __address;
		
		[XmlIgnore]
		public string address
		{ 
			get { return __address; }
			set { __address = value; }
		}

		[XmlElement(ElementName="zipCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __zipCode;
		
		[XmlIgnore]
		public string zipCode
		{ 
			get { return __zipCode; }
			set { __zipCode = value; }
		}

		public contactPerson()
		{
		}
	}


	[XmlType(TypeName="visitPerson",Namespace=Declarations.SchemaVersion),Serializable]
	public class visitPerson
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return personCollection.GetEnumerator();
		}

		public person Add(person obj)
		{
			return personCollection.Add(obj);
		}

		[XmlIgnore]
		public person this[int index]
		{
			get { return (person) personCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return personCollection.Count; }
        }

        public void Clear()
		{
			personCollection.Clear();
        }

		public person Remove(int index) 
		{ 
            person obj = personCollection[index];
            personCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            personCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(person),ElementName="person",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public personCollection __personCollection;
		
		[XmlIgnore]
		public personCollection personCollection
		{
			get
			{
				if (__personCollection == null) __personCollection = new personCollection();
				return __personCollection;
			}
			set {__personCollection = value;}
		}

		public visitPerson()
		{
		}
	}


	[XmlType(TypeName="person",Namespace=Declarations.SchemaVersion),Serializable]
	public class person
	{

		[XmlElement(ElementName="name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlElement(ElementName="namePinyin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __namePinyin;
		
		[XmlIgnore]
		public string namePinyin
		{ 
			get { return __namePinyin; }
			set { __namePinyin = value; }
		}

		[XmlElement(ElementName="credentials",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __credentials;
		
		[XmlIgnore]
		public string credentials
		{ 
			get { return __credentials; }
			set { __credentials = value; }
		}

		[XmlElement(ElementName="credentialsType",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __credentialsType;
		
		[XmlIgnore]
		public string credentialsType
		{ 
			get { return __credentialsType; }
			set { __credentialsType = value; }
		}

		[XmlElement(ElementName="defined1Value",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __defined1Value;
		
		[XmlIgnore]
		public string defined1Value
		{ 
			get { return __defined1Value; }
			set { __defined1Value = value; }
		}

		[XmlElement(ElementName="defined2Value",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __defined2Value;
		
		[XmlIgnore]
		public string defined2Value
		{ 
			get { return __defined2Value; }
			set { __defined2Value = value; }
		}

		public person()
		{
		}
	}


	[XmlType(TypeName="GetProductByQunarRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class GetProductByQunarRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(ElementName="method",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __method;
		
		[XmlIgnore]
		public string method
		{ 
			get { return __method; }
			set { __method = value; }
		}

		[XmlElement(ElementName="currentPage",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __currentPage;
		
		[XmlIgnore]
		public string currentPage
		{ 
			get { return __currentPage; }
			set { __currentPage = value; }
		}

		[XmlElement(ElementName="pageSize",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __pageSize;
		
		[XmlIgnore]
		public string pageSize
		{ 
			get { return __pageSize; }
			set { __pageSize = value; }
		}

		[XmlElement(ElementName="resourceId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __resourceId;
		
		[XmlIgnore]
		public string resourceId
		{ 
			get { return __resourceId; }
			set { __resourceId = value; }
		}

		public GetProductByQunarRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="PayOrderForBeforePaySyncRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class PayOrderForBeforePaySyncRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(PayOrderForBeforePaySyncRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public PayOrderForBeforePaySyncRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public PayOrderForBeforePaySyncRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new PayOrderForBeforePaySyncRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public PayOrderForBeforePaySyncRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="PayOrderForBeforePaySyncRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class PayOrderForBeforePaySyncRequestBodyorderInfo
	{

		[XmlElement(ElementName="partnerOrderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerOrderId;
		
		[XmlIgnore]
		public string partnerOrderId
		{ 
			get { return __partnerOrderId; }
			set { __partnerOrderId = value; }
		}

		[XmlElement(ElementName="orderStatus",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderStatus;
		
		[XmlIgnore]
		public string orderStatus
		{ 
			get { return __orderStatus; }
			set { __orderStatus = value; }
		}

		[XmlElement(ElementName="orderPrice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderPrice;
		
		[XmlIgnore]
		public string orderPrice
		{ 
			get { return __orderPrice; }
			set { __orderPrice = value; }
		}

		[XmlElement(ElementName="paymentSerialno",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __paymentSerialno;
		
		[XmlIgnore]
		public string paymentSerialno
		{ 
			get { return __paymentSerialno; }
			set { __paymentSerialno = value; }
		}

		[XmlElement(ElementName="eticketNo",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __eticketNo;
		
		[XmlIgnore]
		public string eticketNo
		{ 
			get { return __eticketNo; }
			set { __eticketNo = value; }
		}

		public PayOrderForBeforePaySyncRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="PushOrderForBeforePaySyncRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class PushOrderForBeforePaySyncRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(PushOrderForBeforePaySyncRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public PushOrderForBeforePaySyncRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public PushOrderForBeforePaySyncRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new PushOrderForBeforePaySyncRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public PushOrderForBeforePaySyncRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="PushOrderForBeforePaySyncRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class PushOrderForBeforePaySyncRequestBodyorderInfo
	{

		[XmlElement(ElementName="partnerOrderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerOrderId;
		
		[XmlIgnore]
		public string partnerOrderId
		{ 
			get { return __partnerOrderId; }
			set { __partnerOrderId = value; }
		}

		[XmlElement(ElementName="orderStatus",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderStatus;
		
		[XmlIgnore]
		public string orderStatus
		{ 
			get { return __orderStatus; }
			set { __orderStatus = value; }
		}

		[XmlElement(ElementName="cancelReason",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __cancelReason;
		
		[XmlIgnore]
		public string cancelReason
		{ 
			get { return __cancelReason; }
			set { __cancelReason = value; }
		}

		[XmlElement(Type=typeof(PushOrderForBeforePaySyncRequestBodyorderInfocontactPerson),ElementName="contactPerson",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public PushOrderForBeforePaySyncRequestBodyorderInfocontactPerson __contactPerson;
		
		[XmlIgnore]
		public PushOrderForBeforePaySyncRequestBodyorderInfocontactPerson contactPerson
		{
			get
			{
				if (__contactPerson == null) __contactPerson = new PushOrderForBeforePaySyncRequestBodyorderInfocontactPerson();		
				return __contactPerson;
			}
			set {__contactPerson = value;}
		}

		[XmlElement(Type=typeof(PushOrderForBeforePaySyncRequestBodyorderInfovisitPerson),ElementName="visitPerson",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPerson __visitPerson;
		
		[XmlIgnore]
		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPerson visitPerson
		{
			get
			{
				if (__visitPerson == null) __visitPerson = new PushOrderForBeforePaySyncRequestBodyorderInfovisitPerson();		
				return __visitPerson;
			}
			set {__visitPerson = value;}
		}

		[XmlElement(ElementName="orderRemark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderRemark;
		
		[XmlIgnore]
		public string orderRemark
		{ 
			get { return __orderRemark; }
			set { __orderRemark = value; }
		}

		public PushOrderForBeforePaySyncRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="PushOrderForBeforePaySyncRequestBodyorderInfocontactPerson",Namespace=Declarations.SchemaVersion),Serializable]
	public class PushOrderForBeforePaySyncRequestBodyorderInfocontactPerson
	{

		[XmlElement(ElementName="name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlElement(ElementName="namePinyin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __namePinyin;
		
		[XmlIgnore]
		public string namePinyin
		{ 
			get { return __namePinyin; }
			set { __namePinyin = value; }
		}

		[XmlElement(ElementName="mobile",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __mobile;
		
		[XmlIgnore]
		public string mobile
		{ 
			get { return __mobile; }
			set { __mobile = value; }
		}

		[XmlElement(ElementName="email",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __email;
		
		[XmlIgnore]
		public string email
		{ 
			get { return __email; }
			set { __email = value; }
		}

		[XmlElement(ElementName="address",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __address;
		
		[XmlIgnore]
		public string address
		{ 
			get { return __address; }
			set { __address = value; }
		}

		[XmlElement(ElementName="zipCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __zipCode;
		
		[XmlIgnore]
		public string zipCode
		{ 
			get { return __zipCode; }
			set { __zipCode = value; }
		}

		public PushOrderForBeforePaySyncRequestBodyorderInfocontactPerson()
		{
		}
	}


	[XmlType(TypeName="PushOrderForBeforePaySyncRequestBodyorderInfovisitPerson",Namespace=Declarations.SchemaVersion),Serializable]
	public class PushOrderForBeforePaySyncRequestBodyorderInfovisitPerson
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return personCollection.GetEnumerator();
		}

		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson Add(PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			return personCollection.Add(obj);
		}

		[XmlIgnore]
		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson this[int index]
		{
			get { return (PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson) personCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return personCollection.Count; }
        }

        public void Clear()
		{
			personCollection.Clear();
        }

		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson Remove(int index) 
		{ 
            PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj = personCollection[index];
            personCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            personCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson),ElementName="person",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonpersonCollection __personCollection;
		
		[XmlIgnore]
		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonpersonCollection personCollection
		{
			get
			{
				if (__personCollection == null) __personCollection = new PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonpersonCollection();
				return __personCollection;
			}
			set {__personCollection = value;}
		}

		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPerson()
		{
		}
	}


	[XmlType(TypeName="PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson",Namespace=Declarations.SchemaVersion),Serializable]
	public class PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson
	{

		[XmlElement(ElementName="name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlElement(ElementName="namePinyin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __namePinyin;
		
		[XmlIgnore]
		public string namePinyin
		{ 
			get { return __namePinyin; }
			set { __namePinyin = value; }
		}

		[XmlElement(ElementName="credentials",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __credentials;
		
		[XmlIgnore]
		public string credentials
		{ 
			get { return __credentials; }
			set { __credentials = value; }
		}

		[XmlElement(ElementName="credentialsType",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __credentialsType;
		
		[XmlIgnore]
		public string credentialsType
		{ 
			get { return __credentialsType; }
			set { __credentialsType = value; }
		}

		[XmlElement(ElementName="defined1Value",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __defined1Value;
		
		[XmlIgnore]
		public string defined1Value
		{ 
			get { return __defined1Value; }
			set { __defined1Value = value; }
		}

		[XmlElement(ElementName="defined2Value",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __defined2Value;
		
		[XmlIgnore]
		public string defined2Value
		{ 
			get { return __defined2Value; }
			set { __defined2Value = value; }
		}

		public PushOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson()
		{
		}
	}


	[XmlType(TypeName="ApplyProductSaleBySupplierRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class ApplyProductSaleBySupplierRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(ElementName="resourceId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __resourceId;
		
		[XmlIgnore]
		public string resourceId
		{ 
			get { return __resourceId; }
			set { __resourceId = value; }
		}

		public ApplyProductSaleBySupplierRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="NoticeProductChangedRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class NoticeProductChangedRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(ElementName="resourceId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __resourceId;
		
		[XmlIgnore]
		public string resourceId
		{ 
			get { return __resourceId; }
			set { __resourceId = value; }
		}

		public NoticeProductChangedRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="ApplyOrderRefundBySupplierRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class ApplyOrderRefundBySupplierRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(ApplyOrderRefundBySupplierRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ApplyOrderRefundBySupplierRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public ApplyOrderRefundBySupplierRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new ApplyOrderRefundBySupplierRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public ApplyOrderRefundBySupplierRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="ApplyOrderRefundBySupplierRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class ApplyOrderRefundBySupplierRequestBodyorderInfo
	{

		[XmlElement(ElementName="partnerorderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerorderId;
		
		[XmlIgnore]
		public string partnerorderId
		{ 
			get { return __partnerorderId; }
			set { __partnerorderId = value; }
		}

		[XmlElement(ElementName="orderQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderQuantity;
		
		[XmlIgnore]
		public string orderQuantity
		{ 
			get { return __orderQuantity; }
			set { __orderQuantity = value; }
		}

		[XmlElement(ElementName="refundQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundQuantity;
		
		[XmlIgnore]
		public string refundQuantity
		{ 
			get { return __refundQuantity; }
			set { __refundQuantity = value; }
		}

		[XmlElement(ElementName="refundCharge",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundCharge;
		
		[XmlIgnore]
		public string refundCharge
		{ 
			get { return __refundCharge; }
			set { __refundCharge = value; }
		}

		[XmlElement(ElementName="refundReason",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundReason;
		
		[XmlIgnore]
		public string refundReason
		{ 
			get { return __refundReason; }
			set { __refundReason = value; }
		}

		[XmlElement(ElementName="refundExplain",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundExplain;
		
		[XmlIgnore]
		public string refundExplain
		{ 
			get { return __refundExplain; }
			set { __refundExplain = value; }
		}

		public ApplyOrderRefundBySupplierRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForAfterPaySyncRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class CreateOrderForAfterPaySyncRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(CreateOrderForAfterPaySyncRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForAfterPaySyncRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public CreateOrderForAfterPaySyncRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new CreateOrderForAfterPaySyncRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public CreateOrderForAfterPaySyncRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForAfterPaySyncRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForAfterPaySyncRequestBodyorderInfo
	{

		[XmlElement(ElementName="orderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderId;
		
		[XmlIgnore]
		public string orderId
		{ 
			get { return __orderId; }
			set { __orderId = value; }
		}

		[XmlElement(Type=typeof(CreateOrderForAfterPaySyncRequestBodyorderInfoproduct),ElementName="product",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForAfterPaySyncRequestBodyorderInfoproduct __product;
		
		[XmlIgnore]
		public CreateOrderForAfterPaySyncRequestBodyorderInfoproduct product
		{
			get
			{
				if (__product == null) __product = new CreateOrderForAfterPaySyncRequestBodyorderInfoproduct();		
				return __product;
			}
			set {__product = value;}
		}

		[XmlElement(Type=typeof(CreateOrderForAfterPaySyncRequestBodyorderInfocontactPerson),ElementName="contactPerson",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForAfterPaySyncRequestBodyorderInfocontactPerson __contactPerson;
		
		[XmlIgnore]
		public CreateOrderForAfterPaySyncRequestBodyorderInfocontactPerson contactPerson
		{
			get
			{
				if (__contactPerson == null) __contactPerson = new CreateOrderForAfterPaySyncRequestBodyorderInfocontactPerson();		
				return __contactPerson;
			}
			set {__contactPerson = value;}
		}

		[XmlElement(Type=typeof(CreateOrderForAfterPaySyncRequestBodyorderInfovisitPerson),ElementName="visitPerson",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPerson __visitPerson;
		
		[XmlIgnore]
		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPerson visitPerson
		{
			get
			{
				if (__visitPerson == null) __visitPerson = new CreateOrderForAfterPaySyncRequestBodyorderInfovisitPerson();		
				return __visitPerson;
			}
			set {__visitPerson = value;}
		}

		[XmlElement(ElementName="orderQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderQuantity;
		
		[XmlIgnore]
		public string orderQuantity
		{ 
			get { return __orderQuantity; }
			set { __orderQuantity = value; }
		}

		[XmlElement(ElementName="orderPrice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderPrice;
		
		[XmlIgnore]
		public string orderPrice
		{ 
			get { return __orderPrice; }
			set { __orderPrice = value; }
		}

		[XmlElement(ElementName="orderCashBackMoney",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderCashBackMoney;
		
		[XmlIgnore]
		public string orderCashBackMoney
		{ 
			get { return __orderCashBackMoney; }
			set { __orderCashBackMoney = value; }
		}

		[XmlElement(ElementName="orderStatus",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderStatus;
		
		[XmlIgnore]
		public string orderStatus
		{ 
			get { return __orderStatus; }
			set { __orderStatus = value; }
		}

		[XmlElement(ElementName="orderRemark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderRemark;
		
		[XmlIgnore]
		public string orderRemark
		{ 
			get { return __orderRemark; }
			set { __orderRemark = value; }
		}

		[XmlElement(ElementName="orderSource",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderSource;
		
		[XmlIgnore]
		public string orderSource
		{ 
			get { return __orderSource; }
			set { __orderSource = value; }
		}

		[XmlElement(ElementName="paymentSerialno",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __paymentSerialno;
		
		[XmlIgnore]
		public string paymentSerialno
		{ 
			get { return __paymentSerialno; }
			set { __paymentSerialno = value; }
		}

		[XmlElement(ElementName="eticketNo",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __eticketNo;
		
		[XmlIgnore]
		public string eticketNo
		{ 
			get { return __eticketNo; }
			set { __eticketNo = value; }
		}

		public CreateOrderForAfterPaySyncRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForAfterPaySyncRequestBodyorderInfoproduct",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForAfterPaySyncRequestBodyorderInfoproduct
	{

		[XmlElement(ElementName="resourceId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __resourceId;
		
		[XmlIgnore]
		public string resourceId
		{ 
			get { return __resourceId; }
			set { __resourceId = value; }
		}

		[XmlElement(ElementName="productName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __productName;
		
		[XmlIgnore]
		public string productName
		{ 
			get { return __productName; }
			set { __productName = value; }
		}

		[XmlElement(ElementName="visitDate",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __visitDate;
		
		[XmlIgnore]
		public string visitDate
		{ 
			get { return __visitDate; }
			set { __visitDate = value; }
		}

		[XmlElement(ElementName="sellPrice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __sellPrice;
		
		[XmlIgnore]
		public string sellPrice
		{ 
			get { return __sellPrice; }
			set { __sellPrice = value; }
		}

		[XmlElement(ElementName="cashBackMoney",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __cashBackMoney;
		
		[XmlIgnore]
		public string cashBackMoney
		{ 
			get { return __cashBackMoney; }
			set { __cashBackMoney = value; }
		}

		public CreateOrderForAfterPaySyncRequestBodyorderInfoproduct()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForAfterPaySyncRequestBodyorderInfocontactPerson",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForAfterPaySyncRequestBodyorderInfocontactPerson
	{

		[XmlElement(ElementName="name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlElement(ElementName="namePinyin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __namePinyin;
		
		[XmlIgnore]
		public string namePinyin
		{ 
			get { return __namePinyin; }
			set { __namePinyin = value; }
		}

		[XmlElement(ElementName="mobile",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __mobile;
		
		[XmlIgnore]
		public string mobile
		{ 
			get { return __mobile; }
			set { __mobile = value; }
		}

		[XmlElement(ElementName="email",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __email;
		
		[XmlIgnore]
		public string email
		{ 
			get { return __email; }
			set { __email = value; }
		}

		[XmlElement(ElementName="address",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __address;
		
		[XmlIgnore]
		public string address
		{ 
			get { return __address; }
			set { __address = value; }
		}

		[XmlElement(ElementName="zipCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __zipCode;
		
		[XmlIgnore]
		public string zipCode
		{ 
			get { return __zipCode; }
			set { __zipCode = value; }
		}

		public CreateOrderForAfterPaySyncRequestBodyorderInfocontactPerson()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForAfterPaySyncRequestBodyorderInfovisitPerson",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForAfterPaySyncRequestBodyorderInfovisitPerson
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return personCollection.GetEnumerator();
		}

		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson Add(CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			return personCollection.Add(obj);
		}

		[XmlIgnore]
		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson this[int index]
		{
			get { return (CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson) personCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return personCollection.Count; }
        }

        public void Clear()
		{
			personCollection.Clear();
        }

		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson Remove(int index) 
		{ 
            CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson obj = personCollection[index];
            personCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            personCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson),ElementName="person",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonpersonCollection __personCollection;
		
		[XmlIgnore]
		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonpersonCollection personCollection
		{
			get
			{
				if (__personCollection == null) __personCollection = new CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonpersonCollection();
				return __personCollection;
			}
			set {__personCollection = value;}
		}

		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPerson()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson
	{

		[XmlElement(ElementName="name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlElement(ElementName="namePinyin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __namePinyin;
		
		[XmlIgnore]
		public string namePinyin
		{ 
			get { return __namePinyin; }
			set { __namePinyin = value; }
		}

		[XmlElement(ElementName="credentials",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __credentials;
		
		[XmlIgnore]
		public string credentials
		{ 
			get { return __credentials; }
			set { __credentials = value; }
		}

		[XmlElement(ElementName="credentialsType",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __credentialsType;
		
		[XmlIgnore]
		public string credentialsType
		{ 
			get { return __credentialsType; }
			set { __credentialsType = value; }
		}

		[XmlElement(ElementName="defined1Value",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __defined1Value;
		
		[XmlIgnore]
		public string defined1Value
		{ 
			get { return __defined1Value; }
			set { __defined1Value = value; }
		}

		[XmlElement(ElementName="defined2Value",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __defined2Value;
		
		[XmlIgnore]
		public string defined2Value
		{ 
			get { return __defined2Value; }
			set { __defined2Value = value; }
		}

		public CreateOrderForAfterPaySyncRequestBodyorderInfovisitPersonperson()
		{
		}
	}


	[XmlType(TypeName="GetOrderByQunarRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class GetOrderByQunarRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(ElementName="partnerOrderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerOrderId;
		
		[XmlIgnore]
		public string partnerOrderId
		{ 
			get { return __partnerOrderId; }
			set { __partnerOrderId = value; }
		}

		public GetOrderByQunarRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForBeforePaySyncRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class CreateOrderForBeforePaySyncRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(CreateOrderForBeforePaySyncRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForBeforePaySyncRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public CreateOrderForBeforePaySyncRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new CreateOrderForBeforePaySyncRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public CreateOrderForBeforePaySyncRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForBeforePaySyncRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForBeforePaySyncRequestBodyorderInfo
	{

		[XmlElement(ElementName="orderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderId;
		
		[XmlIgnore]
		public string orderId
		{ 
			get { return __orderId; }
			set { __orderId = value; }
		}

		[XmlElement(Type=typeof(CreateOrderForBeforePaySyncRequestBodyorderInfoproduct),ElementName="product",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForBeforePaySyncRequestBodyorderInfoproduct __product;
		
		[XmlIgnore]
		public CreateOrderForBeforePaySyncRequestBodyorderInfoproduct product
		{
			get
			{
				if (__product == null) __product = new CreateOrderForBeforePaySyncRequestBodyorderInfoproduct();		
				return __product;
			}
			set {__product = value;}
		}

		[XmlElement(Type=typeof(CreateOrderForBeforePaySyncRequestBodyorderInfocontactPerson),ElementName="contactPerson",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForBeforePaySyncRequestBodyorderInfocontactPerson __contactPerson;
		
		[XmlIgnore]
		public CreateOrderForBeforePaySyncRequestBodyorderInfocontactPerson contactPerson
		{
			get
			{
				if (__contactPerson == null) __contactPerson = new CreateOrderForBeforePaySyncRequestBodyorderInfocontactPerson();		
				return __contactPerson;
			}
			set {__contactPerson = value;}
		}

		[XmlElement(Type=typeof(CreateOrderForBeforePaySyncRequestBodyorderInfovisitPerson),ElementName="visitPerson",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPerson __visitPerson;
		
		[XmlIgnore]
		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPerson visitPerson
		{
			get
			{
				if (__visitPerson == null) __visitPerson = new CreateOrderForBeforePaySyncRequestBodyorderInfovisitPerson();		
				return __visitPerson;
			}
			set {__visitPerson = value;}
		}

		[XmlElement(ElementName="orderQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderQuantity;
		
		[XmlIgnore]
		public string orderQuantity
		{ 
			get { return __orderQuantity; }
			set { __orderQuantity = value; }
		}

		[XmlElement(ElementName="orderPrice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderPrice;
		
		[XmlIgnore]
		public string orderPrice
		{ 
			get { return __orderPrice; }
			set { __orderPrice = value; }
		}

		[XmlElement(ElementName="orderCashBackMoney",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderCashBackMoney;
		
		[XmlIgnore]
		public string orderCashBackMoney
		{ 
			get { return __orderCashBackMoney; }
			set { __orderCashBackMoney = value; }
		}

		[XmlElement(ElementName="orderStatus",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderStatus;
		
		[XmlIgnore]
		public string orderStatus
		{ 
			get { return __orderStatus; }
			set { __orderStatus = value; }
		}

		[XmlElement(ElementName="orderRemark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderRemark;
		
		[XmlIgnore]
		public string orderRemark
		{ 
			get { return __orderRemark; }
			set { __orderRemark = value; }
		}

		[XmlElement(ElementName="orderSource",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderSource;
		
		[XmlIgnore]
		public string orderSource
		{ 
			get { return __orderSource; }
			set { __orderSource = value; }
		}

		[XmlElement(ElementName="eticketNo",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __eticketNo;
		
		[XmlIgnore]
		public string eticketNo
		{ 
			get { return __eticketNo; }
			set { __eticketNo = value; }
		}

		public CreateOrderForBeforePaySyncRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForBeforePaySyncRequestBodyorderInfoproduct",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForBeforePaySyncRequestBodyorderInfoproduct
	{

		[XmlElement(ElementName="resourceId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __resourceId;
		
		[XmlIgnore]
		public string resourceId
		{ 
			get { return __resourceId; }
			set { __resourceId = value; }
		}

		[XmlElement(ElementName="productName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __productName;
		
		[XmlIgnore]
		public string productName
		{ 
			get { return __productName; }
			set { __productName = value; }
		}

		[XmlElement(ElementName="visitDate",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __visitDate;
		
		[XmlIgnore]
		public string visitDate
		{ 
			get { return __visitDate; }
			set { __visitDate = value; }
		}

		[XmlElement(ElementName="sellPrice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __sellPrice;
		
		[XmlIgnore]
		public string sellPrice
		{ 
			get { return __sellPrice; }
			set { __sellPrice = value; }
		}

		[XmlElement(ElementName="cashBackMoney",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __cashBackMoney;
		
		[XmlIgnore]
		public string cashBackMoney
		{ 
			get { return __cashBackMoney; }
			set { __cashBackMoney = value; }
		}

		public CreateOrderForBeforePaySyncRequestBodyorderInfoproduct()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForBeforePaySyncRequestBodyorderInfocontactPerson",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForBeforePaySyncRequestBodyorderInfocontactPerson
	{

		[XmlElement(ElementName="name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlElement(ElementName="namePinyin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __namePinyin;
		
		[XmlIgnore]
		public string namePinyin
		{ 
			get { return __namePinyin; }
			set { __namePinyin = value; }
		}

		[XmlElement(ElementName="mobile",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __mobile;
		
		[XmlIgnore]
		public string mobile
		{ 
			get { return __mobile; }
			set { __mobile = value; }
		}

		[XmlElement(ElementName="email",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __email;
		
		[XmlIgnore]
		public string email
		{ 
			get { return __email; }
			set { __email = value; }
		}

		[XmlElement(ElementName="address",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __address;
		
		[XmlIgnore]
		public string address
		{ 
			get { return __address; }
			set { __address = value; }
		}

		[XmlElement(ElementName="zipCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __zipCode;
		
		[XmlIgnore]
		public string zipCode
		{ 
			get { return __zipCode; }
			set { __zipCode = value; }
		}

		public CreateOrderForBeforePaySyncRequestBodyorderInfocontactPerson()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForBeforePaySyncRequestBodyorderInfovisitPerson",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForBeforePaySyncRequestBodyorderInfovisitPerson
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return personCollection.GetEnumerator();
		}

		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson Add(CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj)
		{
			return personCollection.Add(obj);
		}

		[XmlIgnore]
		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson this[int index]
		{
			get { return (CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson) personCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return personCollection.Count; }
        }

        public void Clear()
		{
			personCollection.Clear();
        }

		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson Remove(int index) 
		{ 
            CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson obj = personCollection[index];
            personCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            personCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson),ElementName="person",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonpersonCollection __personCollection;
		
		[XmlIgnore]
		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonpersonCollection personCollection
		{
			get
			{
				if (__personCollection == null) __personCollection = new CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonpersonCollection();
				return __personCollection;
			}
			set {__personCollection = value;}
		}

		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPerson()
		{
		}
	}


	[XmlType(TypeName="CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson",Namespace=Declarations.SchemaVersion),Serializable]
	public class CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson
	{

		[XmlElement(ElementName="name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlElement(ElementName="namePinyin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __namePinyin;
		
		[XmlIgnore]
		public string namePinyin
		{ 
			get { return __namePinyin; }
			set { __namePinyin = value; }
		}

		[XmlElement(ElementName="credentials",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __credentials;
		
		[XmlIgnore]
		public string credentials
		{ 
			get { return __credentials; }
			set { __credentials = value; }
		}

		[XmlElement(ElementName="credentialsType",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __credentialsType;
		
		[XmlIgnore]
		public string credentialsType
		{ 
			get { return __credentialsType; }
			set { __credentialsType = value; }
		}

		[XmlElement(ElementName="defined1Value",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __defined1Value;
		
		[XmlIgnore]
		public string defined1Value
		{ 
			get { return __defined1Value; }
			set { __defined1Value = value; }
		}

		[XmlElement(ElementName="defined2Value",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __defined2Value;
		
		[XmlIgnore]
		public string defined2Value
		{ 
			get { return __defined2Value; }
			set { __defined2Value = value; }
		}

		public CreateOrderForBeforePaySyncRequestBodyorderInfovisitPersonperson()
		{
		}
	}


	[XmlType(TypeName="SendOrderEticketRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class SendOrderEticketRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(SendOrderEticketRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public SendOrderEticketRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public SendOrderEticketRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new SendOrderEticketRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public SendOrderEticketRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="SendOrderEticketRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class SendOrderEticketRequestBodyorderInfo
	{

		[XmlElement(ElementName="partnerOrderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerOrderId;
		
		[XmlIgnore]
		public string partnerOrderId
		{ 
			get { return __partnerOrderId; }
			set { __partnerOrderId = value; }
		}

		[XmlElement(ElementName="phoneNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __phoneNumber;
		
		[XmlIgnore]
		public string phoneNumber
		{ 
			get { return __phoneNumber; }
			set { __phoneNumber = value; }
		}

		public SendOrderEticketRequestBodyorderInfo()
		{
		}
	}


	[XmlType(TypeName="GetProductBySupplierRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class GetProductBySupplierRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(ElementName="resourceId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __resourceId;
		
		[XmlIgnore]
		public string resourceId
		{ 
			get { return __resourceId; }
			set { __resourceId = value; }
		}

		public GetProductBySupplierRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderRefundedByQunarRequestBody",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class NoticeOrderRefundedByQunarRequestBody : ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestBody
	{

		[XmlElement(Type=typeof(NoticeOrderRefundedByQunarRequestBodyorderInfo),ElementName="orderInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public NoticeOrderRefundedByQunarRequestBodyorderInfo __orderInfo;
		
		[XmlIgnore]
		public NoticeOrderRefundedByQunarRequestBodyorderInfo orderInfo
		{
			get
			{
				if (__orderInfo == null) __orderInfo = new NoticeOrderRefundedByQunarRequestBodyorderInfo();		
				return __orderInfo;
			}
			set {__orderInfo = value;}
		}

		public NoticeOrderRefundedByQunarRequestBody() : base()
		{
		}
	}


	[XmlType(TypeName="NoticeOrderRefundedByQunarRequestBodyorderInfo",Namespace=Declarations.SchemaVersion),Serializable]
	public class NoticeOrderRefundedByQunarRequestBodyorderInfo
	{

		[XmlElement(ElementName="partnerorderId",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __partnerorderId;
		
		[XmlIgnore]
		public string partnerorderId
		{ 
			get { return __partnerorderId; }
			set { __partnerorderId = value; }
		}

		[XmlElement(ElementName="refundSeq",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundSeq;
		
		[XmlIgnore]
		public string refundSeq
		{ 
			get { return __refundSeq; }
			set { __refundSeq = value; }
		}

		[XmlElement(ElementName="orderQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderQuantity;
		
		[XmlIgnore]
		public string orderQuantity
		{ 
			get { return __orderQuantity; }
			set { __orderQuantity = value; }
		}

		[XmlElement(ElementName="refundQuantity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundQuantity;
		
		[XmlIgnore]
		public string refundQuantity
		{ 
			get { return __refundQuantity; }
			set { __refundQuantity = value; }
		}

		[XmlElement(ElementName="orderPrice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderPrice;
		
		[XmlIgnore]
		public string orderPrice
		{ 
			get { return __orderPrice; }
			set { __orderPrice = value; }
		}

		[XmlElement(ElementName="refundReason",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundReason;
		
		[XmlIgnore]
		public string refundReason
		{ 
			get { return __refundReason; }
			set { __refundReason = value; }
		}

		[XmlElement(ElementName="refundExplain",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundExplain;
		
		[XmlIgnore]
		public string refundExplain
		{ 
			get { return __refundExplain; }
			set { __refundExplain = value; }
		}

		[XmlElement(ElementName="refundJudgeMark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __refundJudgeMark;
		
		[XmlIgnore]
		public string refundJudgeMark
		{ 
			get { return __refundJudgeMark; }
			set { __refundJudgeMark = value; }
		}

		[XmlElement(ElementName="orderRefundCharge",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __orderRefundCharge;
		
		[XmlIgnore]
		public string orderRefundCharge
		{ 
			get { return __orderRefundCharge; }
			set { __orderRefundCharge = value; }
		}

		public NoticeOrderRefundedByQunarRequestBodyorderInfo()
		{
		}
	}


	[XmlRoot(ElementName="request",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	public class request
	{

		[XmlElement(Type=typeof(ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestHeader),ElementName="header",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestHeader __header;
		
		[XmlIgnore]
		public ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestHeader header
		{
			get
			{
				if (__header == null) __header = new ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.RequestHeader();		
				return __header;
			}
			set {__header = value;}
		}
 

		public request()
		{
		}
	}

    [XmlRoot(ElementName="request",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	public class CreateOrderForBeforePaySyncRequestBodyrequest:request
	{
        [XmlElement(Type = typeof(ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.CreateOrderForBeforePaySyncRequestBody), ElementName = "body", IsNullable = false, Form = XmlSchemaForm.Qualified, Namespace = Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
        public ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.CreateOrderForBeforePaySyncRequestBody __body;
		
		[XmlIgnore]
        public ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.CreateOrderForBeforePaySyncRequestBody body
		{
			get
			{
                if (__body == null) __body = new ETS2.PM.Service.Qunar_Ms.QMRequestDataSchema.CreateOrderForBeforePaySyncRequestBody();		
				return __body;
			}
			set {__body = value;}
		}

        public CreateOrderForBeforePaySyncRequestBodyrequest()
		{
		}
	}
    
}
